export default {
    INSERT_RECIPE: "INSERT_RECIPE",
    OPEN_RECIPE: "OPEN_RECIPE",
    CLOSE_RECIPE: "CLOSE_RECIPE",

    FETCH_RECIPES: "FETCH_RECIPES",
    FETCH_RECIPES_SUCCESS: "FETCH_RECIPES_SUCCESS",
    FETCH_RECIPES_ERROR: "FETCH_RECIPES_ERROR",

    AXIOS_GET: "AXIOS_GET",
    AXIOS_GET_SUCCESS: "AXIOS_GET_SUCCESS",
    AXIOS_GET_ERROR: "AXIOS_GET_ERROR",

    AXIOS_POST: "AXIOS_POST",
    AXIOS_POST_SUCCESS: "AXIOS_POST_SUCCESS",
    AXIOS_POST_ERROR: "AXIOS_POST_ERROR",

    CHANGE_TITLE: "CHANGE_TITLE",
    CHANGE_DESCRIPTION: "CHANGE_DESCRIPTION",

    INSERT_INGREDIENT: "INSERT_INGREDIENT",
    REMOVE_INGREDIENT: "REMOVE_INGREDIENT",
    CHANGE_INGREDIENT_NAME: "CHANGE_INGREDIENT_NAME",
    CHANGE_INGREDIENT_QUANTITY: "CHANGE_INGREDIENT_QUANTITY",
    CHANGE_INGREDIENT_UNIT: "CHANGE_INGREDIENT_UNIT",
    MOVE_INSTRUCTION: "MOVE_INSTRUCTION",

    INSERT_STEP: "INSERT_STEP",
    REMOVE_STEP: "REMOVE_STEP",
    CHANGE_STEP: "CHANGE_STEP",

    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",

    CHANGE_SEARCH_WORD: "CHANGE_SEARCH_WORD",
    SEARCH_RECIPES: "SEARCH_RECIPES",
    SEARCH_RECIPES_SUCCESS: "SEARCH_RECIPES_SUCCESS",
    SEARCH_RECIPES_ERROR: "SEARCH_RECIPES_ERROR",
}